=== maruviraj11/gujarat_vidyapith/MCA 2/WEB-TEC/AISSIGNMENT/xmlschema14/build/web/phonebook.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->



<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="phonebook">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="department" maxOccurs="unbounded">

                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="deptname" type="xs:string"/>
                            <xs:element name="deptphone" type="xs:string"/>
                            <xs:element name="deptemail" type="xs:string"/>

                            <xs:element name="employee" maxOccurs="unbounded">

                                <xs:complexType>
                                    <xs:sequence>

                                        <xs:element name="empid" type="xs:string"/>
                                        <xs:element name="empname" type="xs:string"/>
                                        <xs:element name="empphone" type="xs:string"/>
                                        <xs:element name="empemail" type="xs:string"/>

                                    </xs:sequence>

                                    <xs:attribute name="id" type="xs:ID" use="required"/>

                                </xs:complexType>

                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>

                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== maruviraj11/gujarat_vidyapith/MCA 2/WEB-TEC/AISSIGNMENT/xmlschema14/build/web/phonebook.xml
<?xml version="1.0" encoding="UTF-8"?>

<phonebook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="phonebook.xsd">

    <department>

        <deptname>Computer Science</deptname>
        <deptphone>0791234567</deptphone>
        <deptemail>cs@college.com</deptemail>

        <employee id="e1">
            <empid>101</empid>
            <empname>Viraj Maru</empname>
            <empphone>9876543210</empphone>
            <empemail>viraj@gmail.com</empemail>
        </employee>

        <employee id="e2">
            <empid>102</empid>
            <empname>Rahul Patel</empname>
            <empphone>9876500000</empphone>
            <empemail>rahul@gmail.com</empemail>
        </employee>

    </department>

</phonebook>
