=== maruviraj11/gujarat_vidyapith/MCA 2/WEB-TEC/AISSIGNMENT/xmlschema13/build/web/student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->



<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="studentlist">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">

                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="enrollmentno" type="xs:string"/>

                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="firstname" type="xs:string"/>
                                        <xs:element name="middlename" type="xs:string" minOccurs="0"/>
                                        <xs:element name="lastname" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="study_program">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="BSc"/>
                                        <xs:enumeration value="MSc"/>
                                        <xs:enumeration value="MSW"/>
                                        <xs:enumeration value="MBA"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="enrolment_year">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{4}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                        </xs:sequence>

                        <xs:attribute name="id" type="xs:ID" use="required"/>

                    </xs:complexType>

                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== maruviraj11/gujarat_vidyapith/MCA 2/WEB-TEC/AISSIGNMENT/xmlschema13/build/web/studentlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<studentlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="student.xsd">

    <student id="s1">

        <enrollmentno>101</enrollmentno>

        <name>
            <firstname>Viraj</firstname>
            <middlename>Kumar</middlename>
            <lastname>Maru</lastname>
        </name>

        <study_program>MSc</study_program>

        <enrolment_year>2024</enrolment_year>

    </student>

    <student id="s2">

        <enrollmentno>102</enrollmentno>

        <name>
            <firstname>Rahul</firstname>
            <lastname>Patel</lastname>
        </name>

        <study_program>MBA</study_program>

        <enrolment_year>2023</enrolment_year>

    </student>

</studentlist>
